// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkhvhuuvuzjwobhehsqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFraHZodXV2dXpqd29iaGVoc3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjI5NDgsImV4cCI6MjA2NTYzODk0OH0.9sJoLXREq-1lTHrmEDQBQuFRx25FQP5fjpz4sx806mE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);